CREATE TABLE miniautorizador(
id integer PRIMARY KEY AUTO_INCREMENT NOT NULL ,
Nome VARCHAR(255) NOT NULL,
numCartao VARCHAR(12) NOT NULL ,
senha VARCHAR(4) NOT NULL,
usuario VARCHAR(100) NOT NULL ,
saldo FLOAT NOT NULL
)